name: CI
on: [push, workflow_dispatch]

jobs:
  test:
    env: 
      env_var: “This is a job var”
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello world"
      env: 
        env_var: “This is a step var”
